// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using MonoKey.Infrastructure.Persistence;

#nullable disable

namespace MonoKey.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MonoKeyDbContext))]
    [Migration("20260928181036_EncryptedVaultSync")]
    partial class EncryptedVaultSync
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MonoKey.Domain.Devices.DeviceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceIdentifier")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("LastSeenAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Platform")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "DeviceIdentifier")
                        .IsUnique();

                    b.ToTable("devices", null, t =>
                        {
                            t.HasCheckConstraint("ck_devices_platform", "\"Platform\" >= 1 AND \"Platform\" <= 6");
                        });
                });

            modelBuilder.Entity("MonoKey.Domain.Notifications.NotificationPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DaysBeforeRenewal")
                        .HasColumnType("integer");

                    b.Property<bool>("RenewalRemindersEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("notification_preferences", null, t =>
                        {
                            t.HasCheckConstraint("ck_notification_preferences_days_before", "\"DaysBeforeRenewal\" >= 0 AND \"DaysBeforeRenewal\" <= 365");
                        });
                });

            modelBuilder.Entity("MonoKey.Domain.Profiles.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("MonoKey.Domain.Subscriptions.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("BillingIntervalCode")
                        .HasColumnType("integer");

                    b.Property<int>("BillingIntervalCount")
                        .HasColumnType("integer");

                    b.Property<int>("BillingIntervalUnit")
                        .HasColumnType("integer");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly>("NextRenewalDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "NextRenewalDate");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("subscriptions", null, t =>
                        {
                            t.HasCheckConstraint("ck_subscriptions_amount", "\"Amount\" >= 0");

                            t.HasCheckConstraint("ck_subscriptions_currency_code", "\"CurrencyCode\" ~ '^[A-Z]{3}$'");

                            t.HasCheckConstraint("ck_subscriptions_interval_code", "\"BillingIntervalCode\" = \"BillingIntervalUnit\"");

                            t.HasCheckConstraint("ck_subscriptions_interval_count", "\"BillingIntervalCount\" > 0");

                            t.HasCheckConstraint("ck_subscriptions_interval_unit", "\"BillingIntervalUnit\" >= 1 AND \"BillingIntervalUnit\" <= 4");

                            t.HasCheckConstraint("ck_subscriptions_status", "\"Status\" >= 1 AND \"Status\" <= 3");
                        });
                });

            modelBuilder.Entity("MonoKey.Domain.Vault.VaultKeyEnvelope", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncryptionAlgorithm")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("FormatVersion")
                        .HasColumnType("integer");

                    b.Property<string>("KdfAlgorithm")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("KdfIterations")
                        .HasColumnType("integer");

                    b.Property<int>("KdfMemoryKiB")
                        .HasColumnType("integer");

                    b.Property<int>("KdfParallelism")
                        .HasColumnType("integer");

                    b.Property<byte[]>("MasterWrapNonce")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("MasterWrappedKey")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("RecoveryWrapNonce")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("RecoveryWrappedKey")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("vault_key_envelopes", null, t =>
                        {
                            t.HasCheckConstraint("ck_vault_key_envelopes_format", "\"FormatVersion\" = 1");

                            t.HasCheckConstraint("ck_vault_key_envelopes_kdf_iterations", "\"KdfIterations\" >= 2 AND \"KdfIterations\" <= 10");

                            t.HasCheckConstraint("ck_vault_key_envelopes_kdf_memory", "\"KdfMemoryKiB\" >= 32768 AND \"KdfMemoryKiB\" <= 262144");

                            t.HasCheckConstraint("ck_vault_key_envelopes_kdf_parallelism", "\"KdfParallelism\" >= 1 AND \"KdfParallelism\" <= 4");

                            t.HasCheckConstraint("ck_vault_key_envelopes_revision", "\"Revision\" > 0");
                        });
                });

            modelBuilder.Entity("MonoKey.Domain.Vault.VaultRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Ciphertext")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EncryptionAlgorithm")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("FormatVersion")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<byte[]>("Nonce")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<long>("Revision")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "UpdatedAtUtc");

                    b.ToTable("vault_records", null, t =>
                        {
                            t.HasCheckConstraint("ck_vault_records_format", "\"FormatVersion\" = 1");

                            t.HasCheckConstraint("ck_vault_records_payload", "(\"IsDeleted\" AND octet_length(\"Nonce\") = 0 AND octet_length(\"Ciphertext\") = 0) OR (NOT \"IsDeleted\" AND octet_length(\"Nonce\") = 24 AND octet_length(\"Ciphertext\") BETWEEN 16 AND 262160)");

                            t.HasCheckConstraint("ck_vault_records_revision", "\"Revision\" > 0");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
