import { useState } from "react";
import { generatePassword, passwordEntropyUpperBound, type PasswordOptions } from "@monokey/crypto";
import { useTranslation } from "../i18n/useTranslation";
export function PasswordGenerator({ onUse }: { onUse: (value: string) => void }) {
  const { t, locale }=useTranslation(); const [open,setOpen]=useState(false); const [value,setValue]=useState(""); const [reveal,setReveal]=useState(false); const [status,setStatus]=useState("");
  const [options,setOptions]=useState<PasswordOptions>({length:20,uppercase:true,lowercase:true,digits:true,symbols:true,excludeAmbiguous:true});
  function generate():void { try {setValue(generatePassword(options));setStatus("");} catch {setStatus(locale==="tr"?"En az bir karakter türü seçin.":"Select at least one character class.");} }
  async function copy():Promise<void> { try {await navigator.clipboard.writeText(value);setStatus(t("copied"));setTimeout(()=>void navigator.clipboard.readText().then(current=>current===value?navigator.clipboard.writeText(""):undefined).catch(()=>undefined),30_000);}catch{setStatus(t("copyFailed"));} }
  return <div className="password-generator"><button className="auth-link" type="button" onClick={()=>{setOpen(!open);setValue("");setStatus("");}}>{locale==="tr"?"Güvenli parola üret":"Generate a secure password"}</button>{open && <fieldset className="form"><legend>{t("generate")}</legend><label>{locale==="tr"?"Uzunluk":"Length"}<input type="number" min={16} max={128} value={options.length} onChange={e=>{setOptions({...options,length:Number(e.target.value)});setValue("");}} /></label><div className="actions">{(["uppercase","lowercase","digits","symbols","excludeAmbiguous"] as const).map((key,index)=><label key={key}><input type="checkbox" checked={options[key]} onChange={e=>{setOptions({...options,[key]:e.target.checked});setValue("");}} />{locale==="tr"?["Büyük harf","Küçük harf","Rakam","Sembol","Benzer karakterleri çıkar"][index]:["Uppercase","Lowercase","Digits","Symbols","Exclude ambiguous"][index]}</label>)}</div><button type="button" className="button secondary" onClick={generate}>{t("generate")}</button>{value && <><input aria-label={locale==="tr"?"Üretilen parola":"Generated password"} type={reveal?"text":"password"} readOnly value={value} autoComplete="off" /><small>{locale==="tr"?"Alfabe/uzunluk üst tahmini (ölçülen entropi değildir)":"Alphabet/length upper estimate (not measured entropy)"}: {Math.floor(passwordEntropyUpperBound(options))} bits</small><div className="actions"><button className="button secondary" type="button" onClick={()=>setReveal(!reveal)}>{t(reveal?"hide":"reveal")}</button><button className="button secondary" type="button" onClick={()=>void copy()}>{t("copy")}</button><button className="button" type="button" onClick={()=>{onUse(value);setValue("");setOpen(false);}}>{locale==="tr"?"Bu parolayı kullan":"Use this password"}</button></div></>}{status && <p role="status">{status}</p>}</fieldset>}</div>;
}
