import { useRef, useState } from "react";
import { Button, Platform, Pressable, Text, TextInput, View } from "react-native";
import * as AppleAuthentication from "expo-apple-authentication";
import { sendPasswordResetEmail, createUserWithEmailAndPassword, signInWithEmailAndPassword } from "firebase/auth";
import { authenticationMessage, normalizeLoginEmail, safeAuthCode } from "@monokey/contracts";
import { environment } from "../services/environment";
import { auth, signInWithApple } from "../services/firebase";
import { nativeGoogle, nativeGoogleReady, signInWithNativeGoogle } from "../services/nativeGoogle";
import { Screen } from "../components/Screen";
import { useUi } from "../components/ui";
import { PasswordGenerator } from "../components/PasswordGenerator";
import { useLocalization } from "../localization";
export function AuthScreen() {
 const ui=useUi(),{t,locale}=useLocalization();const [email,setEmail]=useState(""),[password,setPassword]=useState(""),[create,setCreate]=useState(false),[reset,setReset]=useState(false),[error,setError]=useState(""),[busy,setBusy]=useState(false);const pending=useRef(false);
 async function run(action:()=>Promise<unknown>):Promise<void>{if(pending.current)return;pending.current=true;setBusy(true);setError("");try{await action();}catch(e){setError(authenticationMessage(e,locale));}finally{pending.current=false;setBusy(false);}}
 async function authenticate():Promise<void>{const normalized=normalizeLoginEmail(email);if(password.length<6)throw {code:"auth/weak-password"};if(create)await createUserWithEmailAndPassword(auth,normalized,password);else await signInWithEmailAndPassword(auth,normalized,password);setPassword("");}
 async function resetPassword():Promise<void>{const normalized=normalizeLoginEmail(email);auth.languageCode=locale;try{await sendPasswordResetEmail(auth,normalized,{url:process.env.EXPO_PUBLIC_AUTH_CONTINUE_URL || (environment.environment==="dev"?"http://localhost:5173/":environment.environment==="test"?"https://icy-mud-054dd8e0f.4.azurestaticapps.net/":""),handleCodeInApp:false});}catch(e){if(!["auth/user-not-found","auth/invalid-credential"].includes(safeAuthCode(e)))throw e;}setError(locale==="tr"?"Hesap uygunsa sıfırlama bağlantısı gönderildi.":"A reset link was sent if the account is eligible.");}
 const GoogleButton=nativeGoogle?.GoogleSigninButton;
 return <Screen><Text accessibilityRole="header" style={ui.title}>Mono Key</Text><View style={ui.card}><TextInput accessibilityLabel={t("email")} autoCapitalize="none" autoComplete="email" textContentType="emailAddress" keyboardType="email-address" style={ui.input} value={email} onChangeText={setEmail} placeholder={t("email")} />{!reset && <TextInput accessibilityLabel={t("password")} autoComplete={create?"new-password":"current-password"} textContentType={create?"newPassword":"password"} secureTextEntry style={ui.input} value={password} onChangeText={setPassword} placeholder={t("password")} />}{create && !reset && <PasswordGenerator onUse={setPassword} />}{error && <Text accessibilityLiveRegion="polite" style={ui.error}>{error}</Text>}<Button title={reset?t("resetPassword"):t(create?"signUp":"signIn")} disabled={busy} onPress={()=>void run(reset?resetPassword:authenticate)} /><Pressable accessibilityRole="button" disabled={busy} onPress={()=>{setReset(!reset);setPassword("");setError("");}}><Text style={ui.body}>{reset?t("signIn"):locale==="tr"?"Şifremi unuttum":"Forgot password?"}</Text></Pressable>{!reset && <><Button title={t(create?"signIn":"signUp")} disabled={busy} onPress={()=>setCreate(!create)} />{GoogleButton && nativeGoogleReady ? <GoogleButton size={GoogleButton.Size.Wide} accessibilityLabel={locale==="tr"?"Google ile devam et":"Continue with Google"} disabled={busy} onPress={()=>void run(signInWithNativeGoogle)} /> : <><Button title="Google" disabled /><Text style={ui.body}>{t("providerUnavailable")}</Text></>}{Platform.OS==="ios" && process.env.EXPO_PUBLIC_ENABLE_APPLE_SIGN_IN==="true" ? <AppleAuthentication.AppleAuthenticationButton buttonType={AppleAuthentication.AppleAuthenticationButtonType.CONTINUE} buttonStyle={AppleAuthentication.AppleAuthenticationButtonStyle.BLACK} cornerRadius={6} style={{height:48,width:280}} onPress={()=>{if(!busy)void run(signInWithApple);}} /> : <><Button title={t("apple")} disabled /><Text style={ui.body}>{locale==="tr"?"Apple üyeliği ve sağlayıcı kurulumu bekleniyor.":"Apple membership and provider setup pending."}</Text></>}</>}<Text style={ui.body}>{locale==="tr"?"Giriş parolasını sıfırlamak kasa ana parolasını değiştirmez. Kasa için ana parola veya kurtarma kodu gerekir.":"Resetting your sign-in password preserves the vault. Its master passphrase or recovery code is still required."}</Text></View></Screen>;
}
