import {useEffect,useState} from 'react';
import {Button,Text,TextInput,View} from 'react-native';
import {applyActionCode,checkActionCode,confirmPasswordReset,verifyPasswordResetCode} from 'firebase/auth';
import {authenticationMessage,type EmailActionInput} from '@monokey/contracts';
import {auth} from '../services/firebase';
import {Screen} from '../components/Screen';
import {PasswordGenerator} from '../components/PasswordGenerator';
import {useLocalization} from '../localization';
import {useUi} from '../components/ui';
const operations:Record<string,string>={verifyEmail:'VERIFY_EMAIL',recoverEmail:'RECOVER_EMAIL',verifyAndChangeEmail:'VERIFY_AND_CHANGE_EMAIL'};
export function EmailActionScreen({action,onClose}:{action:EmailActionInput;onClose:()=>void}) {
 const {locale}=useLocalization(),ui=useUi();const [ready,setReady]=useState(false),[complete,setComplete]=useState(false),[busy,setBusy]=useState(false),[password,setPassword]=useState(''),[confirmation,setConfirmation]=useState(''),[error,setError]=useState('');
 useEffect(()=>{let active=true;void(async()=>{if(action.mode==='resetPassword')await verifyPasswordResetCode(auth,action.code);else{const info=await checkActionCode(auth,action.code);if(info.operation!==operations[action.mode])throw {code:'auth/invalid-action-code'};}if(active)setReady(true);})().catch(e=>{if(active)setError(authenticationMessage(e,locale));});return()=>{active=false;};},[action,locale]);
 async function confirm():Promise<void>{if(!ready||busy)return;if(action.mode==='resetPassword'&&(password.length<12||password!==confirmation)){setError(locale==='tr'?'En az 12 karakter ve eşleşen parolalar gerekir.':'Use at least 12 characters and matching passwords.');return;}setBusy(true);try{if(action.mode==='resetPassword')await confirmPasswordReset(auth,action.code,password);else await applyActionCode(auth,action.code);setComplete(true);setReady(false);}catch(e){setError(authenticationMessage(e,locale));}finally{setBusy(false);setPassword('');setConfirmation('');}}
 return <Screen><Text style={ui.title}>{locale==='tr'?'Hesap işlemi':'Account action'}</Text><Text style={ui.body}>{locale==='tr'?'Giriş parolası değişse de kasa anahtarı değişmez; kasa ana parolası veya kurtarma kodu gerekir.':'Your vault key is preserved. Its master passphrase or recovery code remains necessary.'}</Text>{!ready&&!error&&!complete&&<Text style={ui.body}>{locale==='tr'?'Bağlantı doğrulanıyor…':'Checking the link…'}</Text>}{error&&<Text accessibilityLiveRegion="polite" style={ui.error}>{error}</Text>}{ready&&<View style={ui.card}>{action.mode==='resetPassword'&&<><TextInput style={ui.input} accessibilityLabel={locale==='tr'?'Yeni giriş parolası':'New sign-in password'} autoComplete="new-password" textContentType="newPassword" secureTextEntry value={password} onChangeText={setPassword} /><PasswordGenerator onUse={setPassword} /><TextInput style={ui.input} accessibilityLabel={locale==='tr'?'Parolayı tekrar girin':'Confirm password'} autoComplete="new-password" textContentType="newPassword" secureTextEntry value={confirmation} onChangeText={setConfirmation} /></>}<Button title={locale==='tr'?'Doğrula':'Confirm'} disabled={busy} onPress={()=>void confirm()} /></View>}{complete&&<Text style={ui.body}>{locale==='tr'?'İşlem tamamlandı.':'Action completed.'}</Text>}<Button title={locale==='tr'?'Girişe dön':'Return to sign-in'} onPress={onClose} /></Screen>;
}
