import { useEffect, useState } from "react";
import { Button, Text, TextInput, View } from "react-native";
import { EmailAuthProvider, reauthenticateWithCredential, sendPasswordResetEmail, signOut, updatePassword, verifyBeforeUpdateEmail, unlink } from "firebase/auth";
import type { Membership, Plan } from "@monokey/contracts";
import { Screen } from "../components/Screen";
import { useUi } from "../components/ui";
import { useTheme, type Appearance } from "../theme";
import { auth } from "../services/firebase";
import { api } from "../services/api";
import { useLocalization } from "../localization";
export function SettingsScreen() {
 const ui=useUi(); const {locale,setLocale,t}=useLocalization();const theme=useTheme();const user=auth.currentUser!; const [name,setName]=useState(""); const [currentPassword,setCurrentPassword]=useState(""); const [email,setEmail]=useState(""); const [password,setPassword]=useState("");const [membership,setMembership]=useState<Membership | null>(null); const [plans,setPlans]=useState<Plan[]>([]);const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);
 useEffect(()=>{let active=true;void Promise.all([api.getProfile(),api.getMembership(),api.getPlans()]).then(([profile,membership,plans])=>{if(active){setName(profile.displayName??"");setMembership(membership);setPlans(plans);}}).catch(()=>{if(active)setMessage(t("saveFailed"));});return()=>{active=false;};},[t]);
 async function action(work:()=>Promise<unknown>,reauth=false):Promise<void> {setBusy(true);try{if(reauth){if(!user.email)throw new Error("Email required");await reauthenticateWithCredential(user,EmailAuthProvider.credential(user.email,currentPassword));}await work();await user.reload();await user.getIdToken(true);setCurrentPassword("");setPassword("");setMessage(t("save"));}catch{setMessage(t("authFailed"));}finally{setBusy(false);}}
 return <Screen><Text style={ui.title}>{t("settings")}</Text><View style={ui.card}><Text style={ui.heading}>{t("appearanceLanguage")}</Text><View style={ui.row}><Button title="Türkçe" disabled={locale==="tr"} onPress={()=>setLocale("tr")}/><Button title="English" disabled={locale==="en"} onPress={()=>setLocale("en")}/></View><View style={ui.row}>{(["system","light","dark"] as Appearance[]).map(value=><Button key={value} title={t(value)} disabled={theme.appearance===value} onPress={()=>theme.setAppearance(value)}/>)}</View></View>
 <View style={ui.card}><Text style={ui.heading}>{t("membership")}: {membership?.plan??"—"}</Text>{plans.map(plan=><Text key={plan.id} style={ui.body}>{plan.id} · {plan.displayPrice??"—"}</Text>)}<Text style={ui.body}>{t("checkoutUnavailable")}</Text></View>
 <View style={ui.card}><Text style={ui.heading}>{user.email}</Text><TextInput accessibilityLabel={t("profile")} style={ui.input} value={name} onChangeText={setName}/><Button title={t("save")} disabled={busy} onPress={()=>void action(()=>api.updateProfile(name))}/><TextInput accessibilityLabel={t("currentPassword")} style={ui.input} secureTextEntry value={currentPassword} onChangeText={setCurrentPassword} placeholder={t("currentPassword")}/><TextInput accessibilityLabel={t("newEmail")} style={ui.input} autoCapitalize="none" value={email} onChangeText={setEmail} placeholder={t("newEmail")}/><Button title={t("verifyEmail")} disabled={busy||!email} onPress={()=>void action(()=>verifyBeforeUpdateEmail(user,email),true)}/><TextInput accessibilityLabel={t("newPassword")} style={ui.input} secureTextEntry value={password} onChangeText={setPassword} placeholder={t("newPassword")}/><Button title={t("newPassword")} disabled={busy||password.length<6} onPress={()=>void action(()=>updatePassword(user,password),true)}/><Button title={t("resetPassword")} disabled={busy||!user.email} onPress={()=>void action(()=>sendPasswordResetEmail(auth,user.email!))}/>
 {user.providerData.map(provider=><View key={provider.providerId} style={ui.row}><Text style={ui.body}>{provider.providerId}</Text><Button title={t("delete")} disabled={busy||user.providerData.filter(other=>other.providerId!==provider.providerId && (other.providerId!=="password"||user.emailVerified)).length===0} onPress={()=>void action(()=>unlink(user,provider.providerId),true)}/></View>)}<Text style={ui.body}>{t("providerUnavailable")}</Text><Button title="Google" disabled/><Button title="Apple" disabled/>{message?<Text accessibilityLiveRegion="polite" style={ui.body}>{message}</Text>:null}<Button title={t("signOut")} onPress={()=>void signOut(auth)}/></View></Screen>;
}
