import {mkdir,readFile,writeFile,cp} from 'node:fs/promises';
import {resolve} from 'node:path';
import {site,content} from './src/content.mjs';
const root=import.meta.dirname,out=resolve(root,'dist');await mkdir(out,{recursive:true});
const escape=value=>String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const production=process.env.MARKETING_INDEXABLE==='true';
const hostedOrigin=process.env.MARKETING_HOST_ORIGIN || 'https://witty-ground-0f7ffb410.1.azurestaticapps.net';
const safeOrigin=new URL(hostedOrigin);if(safeOrigin.protocol!=='https:' || safeOrigin.username || safeOrigin.password || safeOrigin.pathname!=='/' || safeOrigin.search || safeOrigin.hash)throw Error('Marketing host must be an exact HTTPS origin');
const origin=production?site.canonical:safeOrigin.origin;
const ids=['features','security','plans','faq'];
function page(locale,legalPage) {
 const t=content[locale],other=locale==='tr'?'en':'tr';const canonical=`${origin}/${locale}/${legalPage?legalPage+'/':''}`;
 const structured=[{'@context':'https://schema.org','@type':'Organization',name:site.brand,url:site.canonical,logo:`${site.canonical}/logo-mark.svg`},{'@context':'https://schema.org','@type':'SoftwareApplication',name:site.brand,applicationCategory:'SecurityApplication',operatingSystem:'Web, Android, iOS',softwareVersion:'0.1.0',description:t.description,url:site.canonical}];
 const nav=`<a class="brand" href="/${locale}/"><img src="/logo-mark.svg" width="36" height="36" alt="">Mono <strong>Key</strong></a><nav aria-label="${locale==='tr'?'Ana gezinme':'Main navigation'}">${t.nav.map((v,i)=>`<a href="/${locale}/#${ids[i]}">${v}</a>`).join('')}</nav><div class="nav-tools"><a href="/${other}/${legalPage?legalPage+'/':''}" lang="${other}" aria-label="${other==='en'?'Read in English':'Türkçe oku'}">${other.toUpperCase()}</a><button id="theme" type="button" aria-label="${t.theme}">◐</button><a class="button small" href="${site.dashboard}">${locale==='tr'?'Giriş yap':'Sign in'}</a></div>`;
 const body=legalPage?`<section class="legal"><p class="eyebrow">MONO KEY · TEST</p><h1>${t[legalPage==='privacy'?'privacy':'legal']}</h1><p>${t[legalPage==='privacy'?'privacyText':'legalText']}</p><p><a href="${site.contact}">${t.contact}</a></p></section>`:`<section class="hero"><div class="hero-copy"><p class="eyebrow"><span></span>${t.eyebrow}</p><h1>${t.hero[0]}<br><em>${t.hero[1]}</em></h1><p class="intro">${t.intro}</p><div class="cta"><a class="button" href="${site.dashboard}">${t.cta}<span aria-hidden="true">↗</span></a><a class="text-link" href="#features">${t.secondary} <span aria-hidden="true">↓</span></a></div><p class="test-note">${t.test}</p></div><figure class="product-preview"><div class="window-bar"><span>● ● ●</span><span>Mono Key / web / TEST</span><span aria-hidden="true">⌘</span></div><img src="/dashboard-preview.webp" alt="${escape(t.previewAlt)}" width="1425" height="980" fetchpriority="high"><figcaption>${t.preview}</figcaption></figure></section>
 <section class="features" id="features"><div class="section-heading"><p class="eyebrow">MONO KEY</p><h2>${t.featuresTitle}</h2></div><div class="feature-grid">${t.features.map(([n,title,text])=>`<article><span class="number">${n}</span><h3>${title}</h3><p>${text}</p></article>`).join('')}</div></section>
 <section class="security" id="security"><div class="security-mark" aria-hidden="true"><img src="/logo-mark.svg" width="120" height="120" alt=""><span>Argon2id</span><span>XChaCha20-Poly1305</span></div><div><p class="eyebrow">${locale==='tr'?'İSTEMCİDE ŞİFRELEME':'CLIENT-SIDE ENCRYPTION'}</p><h2>${t.securityTitle}</h2><p>${t.security}</p><div class="recovery"><strong>${locale==='tr'?'Kurtarma sizin sorumluluğunuzda':'Recovery stays with you'}</strong><p>${t.recovery}</p></div><small>${t.assurance}</small></div></section>
 <section class="platforms"><h2>${t.platformsTitle}</h2><div class="platform-grid">${t.platforms.map(([title,text])=>`<article><h3>${title}</h3><p>${text}</p></article>`).join('')}</div></section>
 <section class="plans" id="plans"><div><p class="eyebrow">FREE / PRO</p><h2>${t.plansTitle}</h2><p>${t.plansText}</p><a class="text-link" href="${site.dashboard}/membership">${t.planCta} ↗</a></div><div class="plan-grid">${['free','pro'].map(key=>`<article><span>${key.toUpperCase()}</span><h3>${t[key]}</h3><p>${t[key+'Text']}</p><small>${locale==='tr'?'Fiyat yapılandırılmadı':'Price not configured'}</small></article>`).join('')}</div></section>
 <section class="faq" id="faq"><h2>${t.faqTitle}</h2>${t.faq.map(([q,a])=>`<details><summary>${q}<span aria-hidden="true">+</span></summary><p>${a}</p></details>`).join('')}</section><section class="closing"><h2>${t.closing}</h2><a class="button" href="${site.dashboard}">${t.cta} ↗</a><small>${t.test}</small></section>`;
 return `<!doctype html><html lang="${locale}"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark light"><title>${escape(legalPage?t[legalPage==='privacy'?'privacy':'legal']+' — Mono Key':t.title)}</title><meta name="description" content="${escape(t.description)}"><meta name="robots" content="${production?'index,follow':'noindex,nofollow'}"><link rel="canonical" href="${canonical}"><link rel="alternate" hreflang="tr" href="${origin}/tr/${legalPage?legalPage+'/':''}"><link rel="alternate" hreflang="en" href="${origin}/en/${legalPage?legalPage+'/':''}"><link rel="alternate" hreflang="x-default" href="${origin}/tr/${legalPage?legalPage+'/':''}"><meta property="og:type" content="website"><meta property="og:title" content="${escape(t.title)}"><meta property="og:description" content="${escape(t.description)}"><meta property="og:url" content="${canonical}"><meta property="og:locale" content="${locale==='tr'?'tr_TR':'en_US'}"><meta property="og:image" content="${origin}/dashboard-preview.webp"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="/logo-mark.svg" type="image/svg+xml"><link rel="stylesheet" href="/style.css"><script src="/theme.js"></script>${production?`<script type="application/ld+json">${JSON.stringify(structured).replaceAll('<','\\u003c')}</script>`:''}</head><body><a class="skip" href="#main">${t.skip}</a><header>${nav}</header><main id="main">${body}</main><footer><a class="brand" href="/${locale}/">Mono <strong>Key</strong></a><p>© 2026 Mono Key · TEST</p><div><a href="/${locale}/privacy/">${t.privacy}</a><a href="/${locale}/terms/">${t.legal}</a><a href="${site.contact}">${t.contact}</a><a href="${site.repository}">${t.source}</a></div></footer><script src="/interaction.js" defer></script></body></html>`;
}
for(const locale of ['tr','en'])for(const route of ['', 'privacy','terms']){const folder=resolve(out,locale,route);await mkdir(folder,{recursive:true});await writeFile(resolve(folder,'index.html'),page(locale,route));}
await writeFile(resolve(out,'index.html'),page('tr',''));
const urls=['tr/','en/','tr/privacy/','en/privacy/','tr/terms/','en/terms/'];await writeFile(resolve(out,'sitemap.xml'),'<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+(production?urls.map(url=>`<url><loc>${origin}/${url}</loc></url>`).join(''):'')+'</urlset>');
await writeFile(resolve(out,'robots.txt'),production?`User-agent: *\nAllow: /\nSitemap: ${origin}/sitemap.xml\n`:'User-agent: *\nDisallow: /\n');
await cp(resolve(root,'public'),out,{recursive:true});
const config={routes:[{route:'/',redirect:'/tr/',statusCode:302},{route:'/*',headers:{'Cache-Control':'no-store'}}],globalHeaders:{'Content-Security-Policy':"default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self'; connect-src 'none'; frame-src 'none'; object-src 'none'; base-uri 'self'; frame-ancestors 'none'; form-action 'none'",'X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer','X-Frame-Options':'DENY',...(production?{}:{'X-Robots-Tag':'noindex, nofollow'})}};
await writeFile(resolve(out,'staticwebapp.config.json'),JSON.stringify(config,null,2));
await writeFile(resolve(out,'build-version.json'),JSON.stringify({commit:process.env.GITHUB_SHA??'local',indexable:production,canonicalOrigin:origin}));console.log(`Prerendered ${urls.length} localized routes; indexable=${production}`);
