import type { ImageSourcePropType } from "react-native";
export const brandImages: Record<string,ImageSourcePropType> = {
  "apple-account": require("../../../packages/contracts/assets/brands/apple-account.png"),
  "apple-music": require("../../../packages/contracts/assets/brands/apple-music.png"),
  "blu-tv": require("../../../packages/contracts/assets/brands/blu-tv.png"),
  "claude": require("../../../packages/contracts/assets/brands/claude.png"),
  "deezer": require("../../../packages/contracts/assets/brands/deezer.png"),
  "discord": require("../../../packages/contracts/assets/brands/discord.png"),
  "dropbox": require("../../../packages/contracts/assets/brands/dropbox.png"),
  "epic-games": require("../../../packages/contracts/assets/brands/epic-games.png"),
  "facebook": require("../../../packages/contracts/assets/brands/facebook.png"),
  "gemini": require("../../../packages/contracts/assets/brands/gemini.png"),
  "github": require("../../../packages/contracts/assets/brands/github.png"),
  "gmail": require("../../../packages/contracts/assets/brands/gmail.png"),
  "google-account": require("../../../packages/contracts/assets/brands/google-account.png"),
  "hbo-max": require("../../../packages/contracts/assets/brands/hbo-max.png"),
  "iCloud": require("../../../packages/contracts/assets/brands/iCloud.png"),
  "instagram": require("../../../packages/contracts/assets/brands/instagram.png"),
  "mubi": require("../../../packages/contracts/assets/brands/mubi.png"),
  "netflix": require("../../../packages/contracts/assets/brands/netflix.png"),
  "notion": require("../../../packages/contracts/assets/brands/notion.png"),
  "okcupid": require("../../../packages/contracts/assets/brands/okcupid.png"),
  "playstation": require("../../../packages/contracts/assets/brands/playstation.png"),
  "reddit": require("../../../packages/contracts/assets/brands/reddit.png"),
  "riot-games": require("../../../packages/contracts/assets/brands/riot-games.png"),
  "roblox": require("../../../packages/contracts/assets/brands/roblox.png"),
  "shazam": require("../../../packages/contracts/assets/brands/shazam.png"),
  "spotify": require("../../../packages/contracts/assets/brands/spotify.png"),
  "steam": require("../../../packages/contracts/assets/brands/steam.png"),
  "telegram": require("../../../packages/contracts/assets/brands/telegram.png"),
  "tinder": require("../../../packages/contracts/assets/brands/tinder.png"),
  "vodafone": require("../../../packages/contracts/assets/brands/vodafone.png"),
  "whatsapp": require("../../../packages/contracts/assets/brands/whatsapp.png"),
  "youtube-premium": require("../../../packages/contracts/assets/brands/youtube-premium.png"),
  "youtube": require("../../../packages/contracts/assets/brands/youtube.png"),
  "zoom": require("../../../packages/contracts/assets/brands/zoom.png"),
};
