import { useState } from "react";
import { Alert, Button, ScrollView, Text, View } from "react-native";
import { matchesNativeApplication, type NativeAutofillRequest } from "@monokey/contracts";
import { encryptVaultRecord } from "@monokey/crypto";
import { auth } from "../services/firebase";
import { api } from "../services/api";
import { nativeAutofill } from "../services/nativeAutofill";
import { useVaultSession } from "../services/VaultSession";
import { cacheVaultRecords } from "../services/offlineDatabase";
import { useLocalization } from "../localization";
import { useUi } from "./ui";
export function NativeAutofillPanel({request}:{request:NativeAutofillRequest}) {
 const session=useVaultSession(),{locale}=useLocalization(),ui=useUi();const [busy,setBusy]=useState(false),[error,setError]=useState("");
 async function fill(id:string):Promise<void>{const user=auth.currentUser,key=session.key,record=session.records.find(x=>x.encrypted.id===id);if(busy || !nativeAutofill || !user || !key || !session.isCurrent(key) || !record || !matchesNativeApplication(record.plaintext,request))return;setBusy(true);try{await nativeAutofill.complete(request.id,request.packageName,request.certificateSha256,record.plaintext.username!,record.plaintext.password!);session.lock();}catch{setError(locale==="tr"?"İstek süresi doldu veya uygulama kimliği değişti.":"Request expired or application identity changed.");}finally{setBusy(false);}}
 async function bind(id:string):Promise<void>{const user=auth.currentUser,key=session.key,record=session.records.find(x=>x.encrypted.id===id);if(busy || !user || !key || !session.isCurrent(key) || !record || record.encrypted.revision===undefined)return;setBusy(true);try{const plaintext={...record.plaintext,nativeAutofill:{...record.plaintext.nativeAutofill,android:{packageName:request.packageName,certificateSha256:request.certificateSha256}}};const ciphertext=encryptVaultRecord(key,user.uid,id,plaintext);const encrypted=await api.updateVaultRecord({...ciphertext,expectedRevision:record.encrypted.revision});if(!session.isCurrent(key)||auth.currentUser?.uid!==user.uid)return;const records=session.records.map(x=>x.encrypted.id===id?{encrypted,plaintext}:x);session.setRecords(records);await cacheVaultRecords(user.uid,records.map(x=>x.encrypted));}catch{setError(locale==="tr"?"Eşleştirme kaydedilemedi.":"Binding could not be saved.");}finally{setBusy(false);}}
 return <ScrollView style={[ui.card,{maxHeight:300}]} keyboardShouldPersistTaps="handled"><Text style={ui.heading}>{locale==="tr"?"Uygulamada otomatik doldurma":"Fill in an application"}</Text><Text style={ui.body}>{request.packageName}</Text><Text selectable style={ui.body}>{request.certificateSha256}</Text>{!session.key && <Text style={ui.body}>{locale==="tr"?"Devam etmek için kasayı açın.":"Unlock your vault to continue."}</Text>}{session.key && session.records.filter(x=>x.plaintext.kind==="login" && x.plaintext.username && x.plaintext.password).map(record=><View key={record.encrypted.id}><Text style={ui.body}>{record.plaintext.title}</Text>{matchesNativeApplication(record.plaintext,request)?<Button title={locale==="tr"?"Bu kaydı doldur":"Fill this credential"} disabled={busy} onPress={()=>void fill(record.encrypted.id)} />:<Button title={locale==="tr"?"Bu uygulamayla eşleştir":"Bind to this application"} disabled={busy} onPress={()=>Alert.alert(locale==="tr"?"Uygulama kimliğini kontrol edin":"Check the application identity",`${record.plaintext.title}\n${request.packageName}\n${request.certificateSha256}\n${locale==="tr"?"Bu eşleştirme şifreli kasa kaydına kaydedilir. Yalnızca bildiğiniz uygulama için onaylayın.":"This binding is saved inside the encrypted record. Confirm only for an application you recognize."}`,[{text:locale==="tr"?"Vazgeç":"Cancel",style:"cancel"},{text:locale==="tr"?"Eşleştir":"Bind",onPress:()=>void bind(record.encrypted.id)}])} />}</View>)}<Button title={locale==="tr"?"Vazgeç":"Cancel"} onPress={()=>{session.lock();void nativeAutofill?.cancel();}} />{error && <Text style={ui.error}>{error}</Text>}</ScrollView>;
}
