import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { useCostSummaryQuery, useSubscriptionsQuery } from "../../app/api";
import { useTranslation } from "../../i18n/useTranslation";
import { useVaultSession } from "../vault/VaultSession";
import { Icon } from "../../components/Icon";
import { LinkedCredentials } from "../subscriptions/LinkedCredentials";
import { ServiceLogo } from "../../components/ServiceLogo";
import { useRenewalReminders } from "../settings/useRenewalReminders";
export function DashboardPage() {
  const {t,locale}=useTranslation();const subscriptions=useSubscriptionsQuery(undefined);const summary=useCostSummaryQuery(undefined);const {upcoming,preference,enabled}=useRenewalReminders();
  const session=useVaultSession();const [reveal,setReveal]=useState<string|null>(null);const [copyStatus,setCopyStatus]=useState("");
  useEffect(() => { const hidden=():void=>{if(document.visibilityState==="hidden")setReveal(null);}; document.addEventListener("visibilitychange",hidden);return()=>document.removeEventListener("visibilitychange",hidden); },[]);
  const activeCount=subscriptions.data?.items.filter(item=>item.status==="Active").length;
  const passwords=session.records.filter(item=>item.plaintext.kind==="login" && item.plaintext.password);
  const weak=passwords.filter(item=>(item.plaintext.password?.length ?? 0)<16).length;
  const reused=passwords.length-new Set(passwords.map(item=>item.plaintext.password)).size;
  async function copy(value:string):Promise<void> {try{await navigator.clipboard.writeText(value);setCopyStatus(t("copied"));setTimeout(()=>void navigator.clipboard.writeText("").catch(()=>undefined),30000);}catch{setCopyStatus(t("copyFailed"));}}
  return <><section className="summary-grid" aria-label={t("dashboard")}><article className="card metric expense"><span className="muted"><Icon name="subscriptions" size={16}/>{t("monthlySpend")}</span>{summary.isLoading?<strong>—</strong>:summary.data?.length?summary.data.map(item=><strong key={item.currencyCode}>{new Intl.NumberFormat(locale,{style:"currency",currency:item.currencyCode}).format(item.monthlyCost)}</strong>):<strong>—</strong>}<p className="muted">{t("currencySeparate")}</p></article>
    <article className="card metric"><span className="muted"><Icon name="subscriptions" size={16}/>{t("activeSubscriptions")}</span><strong>{activeCount ?? "—"}</strong><footer><span className={upcoming.data?.length?"warning-badge":"muted"}>{upcoming.data?.length ?? 0} {t("upcomingRenewals")}</span><Link to="/subscriptions" aria-label={t("subscriptions")}>→</Link></footer></article>
    <article className="card metric"><span className="muted"><Icon name="shield" size={16}/>{t("vaultHealth")}</span><strong className="success">{session.vaultKey ? weak+reused===0?t("healthy"):t("needsReview"):t("locked")}</strong><footer className="muted">{session.vaultKey?`${passwords.length} ${t("encryptedPasswords")} · ${weak+reused} ${t("needsReview")}`:t("vaultPrivacy")}</footer></article></section>
    {(subscriptions.isLoading||summary.isLoading||upcoming.isLoading||preference.isLoading)&&<p role="status">{t("loading")}</p>}{(subscriptions.isError||summary.isError||upcoming.isError||preference.isError)&&<p className="banner error" role="alert">{t("errorGeneric")} <button className="button secondary" onClick={()=>{void subscriptions.refetch();void summary.refetch();void preference.refetch();if(!upcoming.isUninitialized)void upcoming.refetch();}}>{t("retry")}</button></p>}
    <div className="dashboard-columns"><section><header className="section-heading"><h2>{t("upcomingRenewals")}</h2><Link to="/subscriptions">{t("viewAll")}</Link></header><ul className="list">{upcoming.data?.slice(0,5).map(item=><li className="list-item payment-row" key={item.id}><ServiceLogo name={item.name}/><div className="row-details"><h3>{item.name}</h3><LinkedCredentials subscriptionId={item.id}/><p><Icon name="calendar" size={12}/> {new Intl.DateTimeFormat(locale).format(new Date(item.nextRenewalDate+"T00:00:00"))}</p></div><div className="amount">{new Intl.NumberFormat(locale,{style:"currency",currency:item.currencyCode}).format(item.amount)}<p className="success">{t("active")}</p></div></li>)}</ul>{!enabled&&<p className="card muted">{t("remindersDisabled")}</p>}{enabled&&upcoming.data?.length===0&&<p className="card muted">{t("noRenewals")}</p>}</section>
    <section><header className="section-heading"><h2>{t("frequentPasswords")}</h2><Link to="/vault">{t("goToVault")}</Link></header>{!session.vaultKey?<div className="card vault-preview"><Icon name="lock" size={32}/><h3>{t("locked")}</h3><p className="muted">{t("vaultPrivacy")}</p><Link className="button" to="/vault">{t("unlockVault")}</Link></div>:<ul className="list">{session.records.filter(item=>item.plaintext.favorite).slice(0,3).map(item=><li className="card password-preview" key={item.encrypted.id}><div className="section-heading"><div><h3>{item.plaintext.title}</h3><p className="muted">{item.plaintext.username}</p></div><div className="actions"><button className="icon-button" aria-label={t("reveal")} onClick={()=>setReveal(reveal===item.encrypted.id?null:item.encrypted.id)}><Icon name="eye"/></button><button className="icon-button" aria-label={t("copy")} onClick={()=>void copy(item.plaintext.password ?? "")}><Icon name="copy"/></button></div></div><p className="secret">{reveal===item.encrypted.id?item.plaintext.password:"••••••••••••••••"}</p></li>)}</ul>}{session.vaultKey&&session.records.filter(item=>item.plaintext.favorite).length===0&&<p className="card muted">{t("noFavorites")}</p>}<p role="status">{copyStatus}</p></section></div>
  </>;
}
