import {execFileSync} from 'node:child_process';
import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {content,site} from './content.mjs';
test('localized navigation and factual delivery status',()=>{for(const locale of ['tr','en']){const t=content[locale];assert.equal(t.nav.length,4);assert.equal(t.features.length,4);assert.equal(t.platforms.length,4);assert.match(t.platforms[2][1],/imzalama|signing/);assert.match(t.assurance,/TEST/);}assert.equal(site.plans.checkoutAvailable,false);assert.equal(site.plans.displayPrice,null);assert.equal(new URL(site.dashboard).hostname,'icy-mud-054dd8e0f.4.azurestaticapps.net');});
test('pre-rendered localized output is crawlable without Javascript and keeps preview private',async()=>{for(const locale of ['tr','en']){const html=await readFile(new URL('../dist/'+locale+'/index.html',import.meta.url),'utf8');assert.match(html,new RegExp('lang="'+locale+'"'));assert.match(html,/<h1>/);assert.match(html,/rel="canonical"/);assert.match(html,/hreflang="tr"/);assert.match(html,/hreflang="en"/);assert.match(html,/noindex,nofollow/);assert.ok(!html.includes('aggregateRating'));assert.ok(!html.includes('application/ld+json'));}const config=JSON.parse(await readFile(new URL('../dist/staticwebapp.config.json',import.meta.url),'utf8'));assert.equal(config.globalHeaders['X-Robots-Tag'],'noindex, nofollow');assert.match(config.globalHeaders['Content-Security-Policy'],/connect-src 'none'/);});

test('production rendering has accurate structured data and localized canonical URLs',async()=>{
 try{execFileSync(process.execPath,['build.mjs'],{cwd:new URL('..',import.meta.url),env:{...process.env,MARKETING_INDEXABLE:'true'}});
  const html=await readFile(new URL('../dist/en/index.html',import.meta.url),'utf8');assert.match(html,/https:\/\/monokeyapp.com\/en\//);assert.match(html,/index,follow/);const json=html.match(/<script type="application\/ld\+json">([^<]+)<\/script>/)?.[1];assert.ok(json);const schema=JSON.parse(json);assert.equal(schema[1]['@type'],'SoftwareApplication');assert.ok(!schema[1].offers);assert.ok(!schema[1].aggregateRating);
 }finally{execFileSync(process.execPath,['build.mjs'],{cwd:new URL('..',import.meta.url),env:{...process.env,MARKETING_INDEXABLE:'false'}});}
});
