export const site = {
 brand: "Mono Key",
 canonical: "https://monokeyapp.com",
 dashboard: "https://icy-mud-054dd8e0f.4.azurestaticapps.net",
 repository: "https://github.com/ccankayaa/MonoKey",
 contact: "https://github.com/ccankayaa/MonoKey/issues",
 androidTest: "https://appdistribution.firebase.google.com/testerapps/1:1054617929710:android:8da13ab0b5219af345f0ff/releases/5deijon9r2nko",
 plans: {source: "server configuration", checkoutAvailable:false, displayPrice:null},
};
export const content = {
 tr: {
  title:"Mono Key — Şifre yöneticisi ve abonelik yönetimi",
  description:"Mono Key ile parolalarınızı cihazınızda şifreleyin, aboneliklerinizi ve yenilemelerinizi aynı çalışma alanında düzenleyin. TEST web sürümünü keşfedin.",
  nav:["Özellikler","Güvenlik","Planlar","Sık sorulanlar"],
  eyebrow:"DİJİTAL HAYATINIZA BİRAZ DÜZEN",
  hero:["Parolalarınız güvende.","Abonelikleriniz göz önünde."],
  intro:"Biriken hesaplar, unutulan yenilemeler, tekrar kullanılan parolalar. Mono Key, hepsini sakin bir çalışma alanında toplar.",
  cta:"Web uygulamasını dene",test:"TEST ortamını açar",secondary:"Nasıl çalışıyor?",
  preview:"Mono Key web arayüzü · örnek verilerle gerçek ekran",previewAlt:"Mono Key paneli: aylık giderler, abonelikler ve kilitli parola kasası. Tamamen örnek veriler.",
  featuresTitle:"Daha az dağınıklık. Daha fazla kontrol.",
  features:[
   ["01","Parola kasanız, sizin anahtarınız","Giriş bilgilerini istemcide şifreleyin. Kasa anahtarı ve açık parolalar API’ye gönderilmez."],
   ["02","Yenilemeleri tek bakışta görün","Yinelenen giderleri takip edin. Farklı para birimlerini karıştırmadan abonelikleri ve yaklaşan ödemeleri inceleyin."],
   ["03","Her hesap için ayrı parola","Cihazın güvenli rastgeleliğiyle parola üretin. Üretilen değeri yalnızca siz seçtiğinizde bir alana uygulayın."],
   ["04","Tanıdık servisler, yerel simgeler","Bankalar, dijital servisler ve oyunlar için aranabilir katalog. Kasa adresleri bir logo servisine gönderilmez."],
  ],
  securityTitle:"Giriş parolası başka. Kasa ana parolası başka.",
  security:"Firebase hesabınıza girişinizi doğrular. Parola kasası ise Argon2id ve XChaCha20-Poly1305 ile cihazda korunur. Sunucuda yalnızca şifreli kayıtlar ve eşitleme metaverisi bulunur; abonelik verileri uçtan uca şifreli değildir.",
  recovery:"Giriş parolasını sıfırlamak kasayı açmaz. Kasa ana parolanızı veya kurtarma kodunuzu güvenli saklayın. İkisi de kaybolursa ve açık bir cihaz kalmazsa kasa geri getirilemez.",
  assurance:"Bu TEST sürümü bağımsız güvenlik denetiminden geçtiğini veya sertifikalı olduğunu iddia etmez.",
  platformsTitle:"Tek alan. Farklı cihazlar.",
  platforms:[ ["Web","TEST yayını açık. Masaüstü ve mobil tarayıcıdan erişin."],["Android","İmzalı TEST APK’sı davetli Firebase test grubunda. Genel Play Store yayını yok."],["iOS","Simülatör derlemesi mevcut. iPhone kurulumu için Apple imzalama ve cihaz kaydı gerekiyor."],["Tarayıcı uzantısı","Kaynak ve yerel derleme mevcut. Tam HTTPS kaynağı eşleşmesi ve sizin doldurma seçiminiz gerekir."] ],
  plansTitle:"Planlar açık. Fiyat uydurmuyoruz.",
  plansText:"Free ve Pro üyelik modeli sunucuda uygulanır. Güncel kotalar ve varsa fiyatlar uygulamadaki Üyelik ekranından okunur. TEST ortamında ödeme henüz etkin değildir.",
  free:"Free",freeText:"Mevcut temel kasa ve abonelik özelliklerini TEST ortamında keşfedin. Limitler sunucu ayarlarına bağlıdır.",pro:"Pro",proText:"Üyelik altyapısı hazır; satın alma akışı sağlayıcı ve ürün yapılandırması tamamlanınca açılabilir.",planCta:"Güncel planı uygulamada gör",
  faqTitle:"Merak ettikleriniz",
  faq:[
   ["Mono Key bir şifre yöneticisi mi?","Evet. Parola yönetimi için cihazda şifrelenen kasa ile abonelik yönetimini birleştirir. Kasa içeriği, kasayı siz açana kadar görünmez."],
   ["Parolamı unuttum. Ne yapmalıyım?","Hesap giriş parolası Firebase bağlantısıyla sıfırlanır. Kasa için ayrı ana parola veya kurtarma kodu gerekir; destek ekibi kasanızı çözemez."],
   ["Aboneliği buradan iptal edebilir miyim?","Mono Key’de iptal olarak işaretlemek sağlayıcıdaki aboneliği iptal etmez. İptali ilgili servisin hesabında tamamlayın."],
   ["Mobilde başka uygulamalara otomatik doldurma var mı?","Native sağlayıcı entegrasyonu hazırlanıyor; cihaz güvenlik doğrulaması ve platform imzalama tamamlanmadan etkin değildir. Expo Go bu özelliğin yerine geçmez."],
   ["Bu ortamda gerçek verilerimi kullanmalı mıyım?","Bu bir TEST sürümüdür. Değerli hesaplarınızın tek kopyasını burada tutmayın; kurtarma gereksinimlerini ve doğrulama kapsamını değerlendirin."],
  ],
  closing:"Dijital hayatınıza bir anahtar, biraz düzen.",
  privacy:"Gizlilik",legal:"Kullanım koşulları",contact:"İletişim",source:"Kaynak kod",theme:"Görünümü değiştir",skip:"İçeriğe geç",
  privacyText:"Kasa içeriği istemcide şifrelenir. Sunucu hesap kimliğini, abonelik verilerini ve eşitleme metaverisini işleyebilir. Kimlik sağlayıcısı Firebase’dir; barındırma Azure’dadır. Bu site üçüncü taraf analiz veya izleme betiği yüklemez. Hesap ve veri işlemleri için uygulama ayarlarını, soru ve talepler için proje iletişim kanalını kullanın.",
  legalText:"Mono Key şu anda TEST sürümüdür; kullanılabilirlik veya veri kurtarma garantisi verilmez. Kurtarma kodunu ve bağımsız yedeklerinizi güvenli tutun. Sunucunun kasa çözme anahtarı yoktur. Servis marka adları ilgili sahiplerine aittir; bir ortaklık veya onay anlamına gelmez. Ticari fiyat veya aktif satın alma taahhüdü bulunmaz.",
 },
 en: {
  title:"Mono Key — Password and subscription manager",
  description:"Encrypt passwords on your device and organize subscriptions and renewals in one calm workspace. Explore the Mono Key TEST web application.",
  nav:["Features","Security","Plans","FAQ"],eyebrow:"A LITTLE ORDER FOR YOUR DIGITAL LIFE",
  hero:["Passwords protected.","Subscriptions in sight."],intro:"Growing account lists, forgotten renewals, reused passwords. Mono Key brings them into one calm workspace.",
  cta:"Try the web application",test:"Opens the TEST environment",secondary:"How it works",
  preview:"Actual Mono Key web interface · illustrative data",previewAlt:"Mono Key dashboard showing monthly costs, subscriptions and a locked password vault. Illustrative data only.",
  featuresTitle:"Less clutter. More control.",features:[
   ["01","Your vault. Your key.","Encrypt credentials on the client. Vault keys and plaintext passwords never go to the API."],
   ["02","Renewals at a glance","Track recurring costs and upcoming payments while keeping different currencies separate."],
   ["03","A different password for every account","Generate passwords with secure device randomness. Apply a generated value only when you choose."],
   ["04","Familiar services. Local icons.","Search banks, digital services and games. Your vault URLs are never sent to a logo service."],
  ],securityTitle:"Sign-in password and vault passphrase are separate.",security:"Firebase verifies your account sign-in. Argon2id and XChaCha20-Poly1305 protect the vault on your device. The server holds ciphertext and synchronization metadata; subscription data is not end-to-end encrypted.",
  recovery:"Resetting your sign-in password cannot unlock the vault. Keep its master passphrase or recovery code safe. If both are lost and no device remains unlocked, recovery is impossible.",assurance:"This TEST release does not claim an independent security audit or certification.",
  platformsTitle:"One workspace. Different devices.",platforms:[["Web","TEST deployment available in desktop and mobile browsers."],["Android","Signed TEST APK available to invited Firebase testers. No public Play Store release."],["iOS","Simulator build available. iPhone installation requires Apple signing and device registration."],["Browser extension","Source and local builds available. Filling requires an exact HTTPS origin match and your explicit action."]],
  plansTitle:"Real plans. No invented prices.",plansText:"Free and Pro membership are implemented on the server. The application Membership screen reads current quotas and configured prices. TEST checkout is currently disabled.",free:"Free",freeText:"Explore core vault and subscription features in TEST. Limits are controlled by server configuration.",pro:"Pro",proText:"Membership infrastructure exists; purchasing can open after provider and product configuration is complete.",planCta:"View current plans in the app",
  faqTitle:"Questions, answered",faq:[["Is Mono Key a password manager?","Yes. It combines a client-encrypted password vault with subscription management. Vault content stays hidden until you unlock it."],["What happens if I forget my password?","Firebase can reset your account sign-in password. The vault still requires its separate master passphrase or recovery code; support cannot decrypt it."],["Can I cancel subscriptions here?","Marking a subscription cancelled in Mono Key does not cancel it with the provider. Complete cancellation in the service account."],["Can mobile autofill other applications?","Native provider integration is being prepared and remains disabled pending device security verification and platform signing. Expo Go is not a substitute."],["Should I use real valuable data in this environment?","This is a TEST release. Keep independent copies of valuable credentials and evaluate recovery requirements and verification limits."]],closing:"One key. A little more order.",privacy:"Privacy",legal:"Terms of use",contact:"Contact",source:"Source code",theme:"Change appearance",skip:"Skip to content",
  privacyText:"Vault content is encrypted on the client. The server can process account identity, subscription data and synchronization metadata. Firebase provides identity and Azure provides hosting. This site loads no third-party analytics or tracking scripts. Use application settings for account/data actions and the project contact channel for questions and requests.",legalText:"Mono Key is a TEST release without an availability or recovery guarantee. Keep your recovery code and independent backups safe. The server has no vault decryption key. Service brands belong to their owners and imply no partnership or endorsement. No commercial price or active purchase commitment is published.",
 },
};
